// constants.js
// Constants for Tennis game
// Ben Reinherz 2026

TENNIS_GAME.CONSTANTS = {};

// Grid constants
TENNIS_GAME.CONSTANTS.GRID_WIDTH = 28;
TENNIS_GAME.CONSTANTS.GRID_HEIGHT = 28;
TENNIS_GAME.CONSTANTS.GRID_BG_COLOR = 0x617d74;

// Player general constants
TENNIS_GAME.CONSTANTS.PLAYER_SPAWN_X = TENNIS_GAME.CONSTANTS.GRID_WIDTH - 3;
TENNIS_GAME.CONSTANTS.PLAYER_SPAWN_Y = 16;
TENNIS_GAME.CONSTANTS.PLAYER_MIN_Y = 2;
TENNIS_GAME.CONSTANTS.PLAYER_MAX_Y = TENNIS_GAME.CONSTANTS.GRID_HEIGHT - 3;
TENNIS_GAME.CONSTANTS.PLAYER_VELOCITY = 0.5;
TENNIS_GAME.CONSTANTS.PLAYER_MAX_VELOCITY = 2;
TENNIS_GAME.CONSTANTS.PLAYER_ACCELERATION = 0.6;
TENNIS_GAME.CONSTANTS.PLAYER_ACCELERATION_TURNAROUND = 1.2;
TENNIS_GAME.CONSTANTS.PLAYER_SPRITE = [
    {
        offset: [0, 0],
        color: 0x00ffff,
        glyph: "👨".codePointAt(0),
    },
];

// Player racket constants
TENNIS_GAME.CONSTANTS.RACKET_VECTOR = [0, -1];
TENNIS_GAME.CONSTANTS.RACKET_PIVOT_OFFSET = [0, 0];
TENNIS_GAME.CONSTANTS.RACKET_GAP_DISTANCE = 2;
TENNIS_GAME.CONSTANTS.RACKET_LENGTH = 5;
TENNIS_GAME.CONSTANTS.RACKET_COLOR = 0x309142;
TENNIS_GAME.CONSTANTS.RACKET_VELOCITY = 0.5;
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_MARGIN = Math.PI * 0.125;
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_FACTOR = -1;
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_INIT = 0;
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_MIN = 0; //+ (-Math.PI * 0.125);
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_MAX = Math.PI;// + (Math.PI * 0.125);
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_SAVE_STEPS = 50;
TENNIS_GAME.CONSTANTS.RACKET_DECELERATION = 0.2;
TENNIS_GAME.CONSTANTS.RACKET_MIN_HIT_SPEED = 0.4;
TENNIS_GAME.CONSTANTS.RACKET_CHARGE_TIME = 60;
TENNIS_GAME.CONSTANTS.RACKET_CHARGE_COLOR = 0x918e30;
TENNIS_GAME.CONSTANTS.RACKET_CHARGE_FLASH_COLOR = 0xc4c151;
TENNIS_GAME.CONSTANTS.RACKET_CHARGE_FLASH_IN_TIME = 15;
TENNIS_GAME.CONSTANTS.RACKET_CHARGE_FLASH_OUT_TIME = 10;
TENNIS_GAME.CONSTANTS.RACKET_CHARGE_ACTIVE_TIME = 10;

// Player mark constants
TENNIS_GAME.CONSTANTS.MARK_COLOR = 0x355287;
TENNIS_GAME.CONSTANTS.MARK_FLASH_COLOR = 0x70a1fa;
TENNIS_GAME.CONSTANTS.MARK_FLASH_IN_TIME = 10;
TENNIS_GAME.CONSTANTS.MARK_FLASH_OUT_TIME = 20;
TENNIS_GAME.CONSTANTS.MARK_PIVOTS = [
    [11, 0], [13, 0], [15, 0], [17, 0]
]
TENNIS_GAME.CONSTANTS.MARK_COUNT = TENNIS_GAME.CONSTANTS.MARK_PIVOTS.length;
TENNIS_GAME.CONSTANTS.MARK_GLYPH = "X";
TENNIS_GAME.CONSTANTS.MARK_GLYPH_COLOR = 0xffffff;

// Ball constants
TENNIS_GAME.CONSTANTS.BALL_FAST_DEFLECT_ANGLE = Math.PI * 0.5;
TENNIS_GAME.CONSTANTS.BALL_FAST_DEFLECT_SPEED_FACTOR = 1;
TENNIS_GAME.CONSTANTS.BALL_FADE_STEPS = 10;
TENNIS_GAME.CONSTANTS.BALL_SLOW_START_COLOR = 0xff0000;
TENNIS_GAME.CONSTANTS.BALL_SLOW_END_COLOR = 0xa80707;
TENNIS_GAME.CONSTANTS.BALL_FAST_HIT_COLOR = 0x00ffff;
TENNIS_GAME.CONSTANTS.BALL_FAST_HIT_LERP_ALPHA = 1;
TENNIS_GAME.CONSTANTS.BALL_FAST_HIT_CHARGE_COLOR = 0xffff00;
TENNIS_GAME.CONSTANTS.BALL_CHARGE_ALPHA_MULTIPLIER = 2;
TENNIS_GAME.CONSTANTS.BALL_SPAWN_MIN_Y = 4;
TENNIS_GAME.CONSTANTS.BALL_SPAWN_MAX_Y = TENNIS_GAME.CONSTANTS.GRID_HEIGHT - 5;
TENNIS_GAME.CONSTANTS.BALL_TYPE_REGULAR = {
    speedFactor: 1,
    directions: [[1, 0]],
    color: 0x00ff00,
};

// Points constants
TENNIS_GAME.CONSTANTS.POINTS_MULTIPLE = 50;
TENNIS_GAME.CONSTANTS.POINTS_SPEED_MAX = 1000;
TENNIS_GAME.CONSTANTS.POINTS_SPEED_MIN = 100;
TENNIS_GAME.CONSTANTS.POINTS_SPEED_COEFFICIENT = 300;
TENNIS_GAME.CONSTANTS.POINTS_OUT_X_MAX = 2000;
TENNIS_GAME.CONSTANTS.POINTS_OUT_X_MIN = 100;
TENNIS_GAME.CONSTANTS.POINTS_COLOR_MAX = 0xfc8c03;
TENNIS_GAME.CONSTANTS.POINTS_COLOR_MIN = 0x03fc39;

// Level constants
TENNIS_GAME.CONSTANTS.COURT_COLOR = 0x72cf6b;
TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR = 0xffffff;
TENNIS_GAME.CONSTANTS.LEVEL_BG_COLOR = 0x8EDFFF;
TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW = [
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
    // TENNIS_GAME.CONSTANTS.COURT_COLOR,
];
TENNIS_GAME.CONSTANTS.LEVEL_BACKGROUND = [
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    [
        TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
        TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
        TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
        TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
        TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
        TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
        TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
        TENNIS_GAME.CONSTANTS.COURT_COLOR,
    ],
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.LEVEL_COURT_ROW,
    TENNIS_GAME.CONSTANTS.COURT_LINE_COLOR,
    TENNIS_GAME.CONSTANTS.COURT_COLOR,
]
TENNIS_GAME.CONSTANTS.LEVEL_STATUS_COLOR = 0xffffff;
TENNIS_GAME.CONSTANTS.LEVEL_STATUS_POINT_FLASH_COLOR = 0x00ff00;
TENNIS_GAME.CONSTANTS.LEVEL_STATUS_POINT_FLASH_GOLD_COLOR = 0xffff00;
TENNIS_GAME.CONSTANTS.LEVEL_STATUS_FLASH_IN_TIME = 3;
TENNIS_GAME.CONSTANTS.LEVEL_STATUS_FLASH_OUT_TIME = 20;
TENNIS_GAME.CONSTANTS.LEVEL_GAME_OVER_COLOR = 0xffffff;
TENNIS_GAME.CONSTANTS.LEVEL_TUTORIAL_STATUS = "READY? SWING!";
TENNIS_GAME.CONSTANTS.LEVEL_TUTORIAL_STATUS_COLOR = 0xffff00;
TENNIS_GAME.CONSTANTS.LEVEL_TUTORIAL_READY = "START!";
TENNIS_GAME.CONSTANTS.LEVEL_TUTORIAL_READY_COLOR = 0x00ff00;
TENNIS_GAME.CONSTANTS.LEVEL_TUTORIAL_READY_TIMER = 60;
TENNIS_GAME.CONSTANTS.LEVEL_GROUND_Y = TENNIS_GAME.CONSTANTS.GRID_WIDTH - TENNIS_GAME.CONSTANTS.FROG_HEIGHT - 1;

// Input constants
TENNIS_GAME.CONSTANTS.SWING_TIME_COOLDOWN = 1
TENNIS_GAME.CONSTANTS.MOVE_UP_KEYS = [
    "W".codePointAt(0),
    "w".codePointAt(0),
    PS.KEY_ARROW_UP,
]
TENNIS_GAME.CONSTANTS.MOVE_DOWN_KEYS = [
    "S".codePointAt(0),
    "s".codePointAt(0),
    PS.KEY_ARROW_DOWN,
]
TENNIS_GAME.CONSTANTS.CHARGE_KEYS = [
    " ".codePointAt(0),
]