// constants.js
// Constants for Tennis game
// Ben Reinherz 2026

TENNIS_GAME.CONSTANTS = {};

// Grid constants
TENNIS_GAME.CONSTANTS.GRID_WIDTH = 32;
TENNIS_GAME.CONSTANTS.GRID_HEIGHT = 32;
TENNIS_GAME.CONSTANTS.GRID_BG_COLOR = 0xffffff;

// Player constants
TENNIS_GAME.CONSTANTS.PLAYER_SPAWN_X = 28;
TENNIS_GAME.CONSTANTS.PLAYER_SPAWN_Y = 16;
TENNIS_GAME.CONSTANTS.PLAYER_MIN_Y = 5;
TENNIS_GAME.CONSTANTS.PLAYER_MAX_Y = TENNIS_GAME.CONSTANTS.GRID_HEIGHT - 6;
TENNIS_GAME.CONSTANTS.PLAYER_VELOCITY = 0.7;
TENNIS_GAME.CONSTANTS.PLAYER_MAX_VELOCITY = 2;
TENNIS_GAME.CONSTANTS.PLAYER_ACCELERATION = 0.3;
TENNIS_GAME.CONSTANTS.PLAYER_ACCELERATION_TURNAROUND = 1.2;
TENNIS_GAME.CONSTANTS.PLAYER_SPRITE = [
    {
        offset: [0, 0],
        color: 0xffff00,
    },
    // {
    //     offset: [0, 1],
    //     color: 0xff0000,
    // },
    // {
    //     offset: [0, -1],
    //     color: 0x000000,
    // },
];
TENNIS_GAME.CONSTANTS.RACKET_VECTOR = [0, -1];
TENNIS_GAME.CONSTANTS.RACKET_PIVOT_OFFSET = [0, 0];
TENNIS_GAME.CONSTANTS.RACKET_GAP_DISTANCE = 2;
TENNIS_GAME.CONSTANTS.RACKET_LENGTH = 4;
TENNIS_GAME.CONSTANTS.RACKET_COLOR = 0x309142;
TENNIS_GAME.CONSTANTS.RACKET_VELOCITY = 0.3;
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_FACTOR = -1;
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_INIT = 0;
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_MIN = 0 + (-Math.PI * 0.125);
TENNIS_GAME.CONSTANTS.RACKET_ANGLE_MAX = Math.PI + (Math.PI * 0.125);
TENNIS_GAME.CONSTANTS.RACKET_DECELERATION = 0.15;

// Level constants
TENNIS_GAME.CONSTANTS.LEVEL_BG_COLOR = 0x8EDFFF;
TENNIS_GAME.CONSTANTS.LEVEL_GROUND_Y = TENNIS_GAME.CONSTANTS.GRID_WIDTH - TENNIS_GAME.CONSTANTS.FROG_HEIGHT - 1;

// Input constants
TENNIS_GAME.CONSTANTS.MIN_TIME_GAP = 10
TENNIS_GAME.CONSTANTS.MOVE_UP_KEYS = [
    "W".codePointAt(0),
    "w".codePointAt(0),
    PS.KEY_ARROW_UP,
]
TENNIS_GAME.CONSTANTS.MOVE_DOWN_KEYS = [
    "S".codePointAt(0),
    "s".codePointAt(0),
    PS.KEY_ARROW_DOWN,
]