// constants.js
// Constants for Perlenblocks game
// Ben Reinherz 2025

FROG_GAME.CONSTANTS = {};

// Grid constants
FROG_GAME.CONSTANTS.GRID_WIDTH = 32;
FROG_GAME.CONSTANTS.GRID_HEIGHT = 32;
FROG_GAME.CONSTANTS.GRID_BG_COLOR = 0xffffff;

FROG_GAME.CONSTANTS.FROG_SPAWN = [13, 30];
FROG_GAME.CONSTANTS.FROG_WIDTH = 5;
FROG_GAME.CONSTANTS.FROG_HEIGHT = 5;
FROG_GAME.CONSTANTS.FROG_JUMP_VEL = -0.8;
FROG_GAME.CONSTANTS.FROG_GRAVITY = 0.05;
FROG_GAME.CONSTANTS.FROG_MAX_Y_VEL = 0.5;

FROG_GAME.CONSTANTS.FROG_GREEN = 0x00C000;
FROG_GAME.CONSTANTS.FROG_EYE = 0x000000;
FROG_GAME.CONSTANTS.FROG_TONGUE = 0xFF0000;
FROG_GAME.CONSTANTS.FROG_SPRITE_MAP = [
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0x00,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,

    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_EYE, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_EYE, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,

    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,

    FROG_GAME.CONSTANTS.FROG_GREEN, 0x00,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0x00,
    
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0x00,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
    FROG_GAME.CONSTANTS.FROG_GREEN, 0xFF,
]
FROG_GAME.CONSTANTS.FROG_SPRITE = {
    id: "frog",
    width: FROG_GAME.CONSTANTS.FROG_WIDTH,
    height: FROG_GAME.CONSTANTS.FROG_HEIGHT,
    pixelSize: 2,
    data: FROG_GAME.CONSTANTS.FROG_SPRITE_MAP
};


// Level constants
FROG_GAME.CONSTANTS.LEVEL_BG_COLOR = 0x8EDFFF;
FROG_GAME.CONSTANTS.LEVEL_GROUND_Y = FROG_GAME.CONSTANTS.GRID_WIDTH - FROG_GAME.CONSTANTS.FROG_HEIGHT - 1;

// Input constants
FROG_GAME.CONSTANTS.MIN_TIME_GAP = 10
FROG_GAME.CONSTANTS.MOVE_LEFT_KEYS = [
    "A".codePointAt(0),
    "a".codePointAt(0),
    PS.KEY_ARROW_LEFT,
]
FROG_GAME.CONSTANTS.MOVE_RIGHT_KEYS = [
    "D".codePointAt(0),
    "d".codePointAt(0),
    PS.KEY_ARROW_RIGHT,
]
FROG_GAME.CONSTANTS.JUMP_KEYS = [
    " ".codePointAt(0),
    "W".codePointAt(0),
    "w".codePointAt(0),
]